# config

inherit_gem:
  rubocop-github:
    - config/default_edge.yml
    - config/rails_edge.yml

# custom styles

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
