default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local_env: &local_env
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  <<: *local_env
  database: p_test_development

test:
  <<: *default
  <<: *local_env
  database: p_test_test

production:
  <<: *default
  database: p_test_production
  username: p_test
  password: <%= ENV['P_TEST_DATABASE_PASSWORD'] %>
